services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.batchlearn-api.rule=Host(`apisbatchlearn.siddarammetri.space`)
      - traefik.http.routers.batchlearn-api.entrypoints=web,websecure
      - traefik.http.services.batchlearn-api.loadbalancer.server.port=8000
    networks:
      - dokploy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  dokploy-network:
    external: true
